env:
  global:
    - CC_TEST_REPORTER_ID=c86d1788cc9661317eb0710b8ce2330d1857c84ec71cf5a8db24e466f6b0a7ed
language: python
python:
  # - "2.6"
  # - "2.7"
  # - "3.4"
  # - "3.5"
  - "3.6"
  # PyPy versions
  # - "pypy2.7"
  # - "pypy3.5"
# command to install dependencies
install:
  # - pip install -r requirements_common.txt
  - pip install coverage
# command to run tests
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest
  - coverage run app.py test
after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  - coveralls
